version: '3'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  db-data: